spring:
  application:
    name: ApiGateway-TravelBooking
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8088}"
  cloud:   
    gateway:
      routes:
        - id: Registartion-TravelBooking
          uri: lb://Registartion-TravelBooking
          predicates:
            - Path=/registartion/**
        - id: FlightBookingService
          uri: lb://FlightBookingService
          predicates:
            - Path=/flight/**
        - id: HotelBookingService
          uri: lb://HotelBookingService
          predicates:
            - Path=/hotel/**
        - id: CarRentalService
          uri: lb://CarRentalService
          predicates:
            - Path=/car/**
        - id: PaymentService
          uri: lb://PaymentService
          predicates:
            - Path=/stripe/**
        - id: ItineraryManagementService
          uri: lb://ItineraryManagementService
          predicates:
            - Path=/itinerary/**
        - id: LoyaltyService
          uri: lb://LoyaltyService
          predicates:
            - Path=/loyalty/**

